#spring.application.name=spring-config-server

spring:
  application:
    name: Spring Cloud Config Server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Mirmukhsin/spring-cloud-config

server:
  port: 8888